config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users do
    member do
    get 'tops/index' => 'tops#index'
    get :following, :followers
    
    end
  end
  resources :relationships,  only: [:create, :destroy]
  resources :comments,  only: [:create, :destroy]

  resources :instagrams do
    resources :comments,  only: [:create, :destroy]
  end
  resources :instagrams do
    resources :likes, only: [:create, :destroy]
  end
  
  resources :instagrams do
    resources :relationships, only: [:create, :destroy]
  end

  
  root 'tops#index' 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :instagram
end

app/models/instagram.rb
class Instagram < ApplicationRecord
    mount_uploader :image, ImageUploader
    belongs_to :user
    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
    has_many :comments, dependent: :destroy
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :instagram
  belongs_to :user
  validates_uniqueness_of :instagram_id, scope: :user_id
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :follower, class_name: "User"
    belongs_to :following, class_name: "User"
    validates :follower_id, presence: true
    validates :following_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable
 # Include default devise modules. Others available are:
# :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable
        has_many :instagrams, dependent: :destroy
        validates :name, presence: true
        validates :profile, length: { maximum: 200 }
        has_many :likes, dependent: :destroy
        has_many :liked_instagrams, through: :likes, source: :instagram
        has_many :comments, dependent: :destroy
        mount_uploader :image, ImageUploader
        has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
        has_many :followings, through: :following_relationships
        has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
        has_many :followers, through: :follower_relationships

  def already_liked?(instagram)
    self.likes.exists?(instagram_id: instagram.id)
  end

  def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
  end

  def follow!(other_user)
    following_relationships.create!(following_id: other_user.id)
  end

  def unfollow!(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

protected
    def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :image])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile, :image])
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!

    def create
    instagram = Instagram.find(params[:instagram_id])
        comment = instagram.comments.build
        comment.user_id = current_user.id
        if comment.save
            flash[:success] = "コメントしました"
            redirect_back(fallback_location: root_path) 
        else
            flash[:success] = "コメントできませんでした"
            redirect_back(fallback_location: root_path) 
        end
    end

    def show
        @instagram = Instagram.find(params[:id])
        @comments = @instagram.comments
        @comment = Comment.new

    end


    def destroy
        comment = Comment.find(params[:id])
        comment.destroy
        redirect_back(fallback_location: root_path)
    end
    

    private

    def comment_params
            params.require(:comment).permit(:content) 
    end

end

app/controllers/instagrams_controller.rb
class InstagramsController < ApplicationController
    before_action :authenticate_user!
    def index
        @instagrams = Instagram.all
    end

    def new
        @instagram = Instagram.new
    end

    def create
    instagram =Instagram.new(instagram_params)
    instagram.user_id = current_user.id
        if instagram.save
        redirect_to :action => "index"
        else
        redirect_to :action => "new"
        end
    end
    

    def show
        @instagram = Instagram.find(params[:id])
        @comments = @instagram.comments
        @comment = Comment.new
    end

    def edit
        @instagram = Instagram.find(params[:id])
    end

    def update
    instagram = Instagram.find(params[:id])
        if instagram.update(instagram_params)
            redirect_to :action => "show", :id => instagram.id
        else
            redirect_to :action => "new"
        end
    end

    def destroy
    instagram = Instagram.find(params[:id])
    instagram.destroy
        redirect_to action: :index
    end

    private
    def instagram_params
        params.require(:instagram).permit(:body, :image)
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        like = current_user.likes.create(instagram_id: params[:instagram_id]) 
        redirect_back(fallback_location: root_path)
    end
    
    def destroy
        like = Like.find_by(instagram_id: params[:instagram_id], user_id: current_user.id)
        like.destroy
        redirect_back(fallback_location: root_path)
    end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
    def create
        @user = User.find(params[:relationship][:following_id])
        current_user.follow!(@user)
        redirect_to @user
    end
    
    def destroy
        @user = Relationship.find(params[:id]).following
        current_user.unfollow!(@user)
        redirect_to @user
    end
    end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
    def index
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id]) 
    end

    def following
        @user  = User.find(params[:id])
        @users = @user.followings
        render 'show_follow'
    end

    def followers
        @user  = User.find(params[:id])
        @users = @user.followers
        render 'show_follower'
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/instagrams_helper.rb
module InstagramsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
    def current_user?(user)
        user == current_user
    end
end

app/views/instagrams/edit.html.erb
<%= form_for @instagram do |f| %>
    <%= f.text_field :name, :size => 50 %> 

    <%= f.file_field :image %>
    <%= f.submit "編集する" %>
  <% end %>

app/views/instagrams/index.html.erb
<h1>GeekInstagram</h1>
<h3>投稿一覧</h3>
<h3>投稿を検索</h3>
    <%= form_tag({controller:"instagrams",action:"index"}, method: :get) do %>
    <%= text_field_tag :search %>
    <%= submit_tag '検索する'  %>
<% end %>
<%= link_to "新規投稿へ", new_instagram_path %>
<%= button_to 'ログアウト', destroy_user_session_path, method: :delete %>

<% if user_signed_in? %>
    <%= link_to "マイページへ", user_path(current_user.id) %>
<% end %>
<div class="instagrams-container">
    <% @instagrams.each do |t| %>
    <div class="instagram">
        <%= t.created_at %>
        <%= t.user.email %>
        <%= image_tag t.image_url, size: "250x200" if t.image? %>
        <%= link_to "詳細へ", instagram_path(t.id) %>
<% if user_signed_in? %>
    <% if current_user.already_liked?(t) %>
        <%= link_to instagram_like_path(id: t.id, instagram_id: t.id), method: :delete do %>
            <i class="fas fa-heart"></i><%= t.likes.count %>
        <% end %>
    <% else %>
        <%= link_to instagram_likes_path(id: t.id, instagram_id: t.id), method: :post do %>
            <i class="far fa-heart"></i><%= t.likes.count %>
        <% end %>
    <% end %>
<% else %>
    <i class="far fa-heart"></i><%= t.likes.count %>
<% end %>
    <% if user_signed_in? && current_user.id == t.user_id %>             
        <%= link_to "編集する", edit_instagram_path(t.id) %>
        <%= button_to "削除する", instagram_path(t.id), method: :delete %>
    <% end %> 
</div>
<% end %> 

app/views/instagrams/new.html.erb
<h1>Geekinstagram</h1>
<h3>新規投稿</h3>
<%= form_for @instagram do |f| %>
  <div class="field">
  <%= f.label :名前 %>
  <%= f.text_field :name %>
  <br>
  <%= f.label :画像 %>
  <%= f.file_field :image %>
</div>
<%= f.submit "投稿する" %>
<% end %>
<%= link_to "TOPページに戻る", instagrams_path %>
</div>

app/views/instagrams/show.html.erb
<h1>GeekInstagram</h1>
<h3>投稿詳細</h3>
<div class="instagram">
    <p><%= @instagram.name %></p>
    <p><%= @instagram.body %></p>
    <p><%= @instagram.created_at %></p>
    <%= image_tag @instagram.image_url, size: "250x200" if @instagram.image? %>

    <% if user_signed_in? %>
    <% if current_user.already_liked?(@instagram) %>
        <%= link_to instagram_like_path(@instagram), method: :delete do %>
            <i class="fas fa-heart"></i><%= @instagram.likes.count %>
        <% end %>
    <% else %>
        <%= link_to instagram_likes_path(@instagram), method: :post do %>
            <i class="far fa-heart"></i><%= @instagram.likes.count %>
        <% end %>
    <% end %>
    <% else %>
    <i class="far fa-heart"></i><%= @instagram.likes.count %>
    <% end %>
</div>

<h2>いいねしたユーザー</h2>
<% @instagram.liked_users.each do |user| %>
    <li><%= user.email %></li>
<% end %>

<div class="comment-wrapper">
    <p>コメント一覧</p>
    <% @comments.each do |c| %>
    <div>
        <%= c.user.email unless c.user.blank? %>
        <br>
        <%= c.content %>
    </div>
    <% if user_signed_in? && current_user.id == c.user_id %>
        <%= button_to "削除する", comment_path(c.id), method: :delete %>
    <% end %>
        <br>
<% end %>

<% if user_signed_in? %>
    <%= form_with(model: [@instagram,@comment], local: true) do |f| %>
        <%= f.text_area :content %>
        <%= button_tag type: "submit" do %>
            <i class="far fa-comments"></i> コメントする
        <% end %>
    <% end %>

<% end %>
</div>
<%= link_to "投稿一覧に戻る", instagrams_path %>
<%= link_to "編集する", edit_instagram_path(@instagram.id) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Geekinstagram</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/64ebf5b9f8.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tops/index.html.erb
Geekinstagram
<%= link_to "ログイン", user_session_path %>
<%= link_to "新規登録", new_user_registration_path  %>

app/views/users/_follow.html.erb
<%= form_for(current_user.following_relationships.build(following_id: @user.id)) do |f| %>
    <div><%= f.hidden_field :following_id %></div>
    <%= f.submit "Follow", class: "btn btn-large btn-primary follow-btn" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
<div id="follow_form">
<% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
<% else %>
    <%= render 'follow' %>
<% end %>
</div>
<% end %>  

app/views/users/_stats.html.erb
<% @user ||= current_user %>
    <div class="stats">
        <a href="<%= following_user_path(@user) %>">
        <strong id="following" class="stat">
        <%= @user.followings.count %>
    </strong>

    following
    </a>
        <a href="<%= followers_user_path(@user) %>">
        <strong id="followers" class="stat">
            <%= @user.followers.count %>
        </strong>
    followers
    </a>
</div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.following_relationships.find_by(following_id: @user.id), html: { method: :delete }) do |f| %>
    <%= f.submit "Unfollow", class: "btn btn-large follow-btn" %>
<% end %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<h1>マイページ</h1>
<%= image_tag @user.image_url, size: "250x200" if @user.image? %>
<p>名前 : <%= @user.name %></p>
<p>メールアドレス : <%= @user.email %></p>
<p>プロフィール : <%= @user.profile %></p>

<% if current_user.id == @user.id %>
    <%= link_to "編集する", edit_user_registration_path %>
<% end %>

<h2>ユーザーの投稿一覧</h2>
<% @user.instagrams.each do |t| %>
    <%= t.user.name %>
    <%= t.body %>
    
<% end %>

<h2>ユーザーがいいねした投稿一覧</h2>
<% @user.liked_instagrams.each do |t| %>
    <%= t.user.name %>
    <%= t.body %>
<% end %>
<!-- ここまで-->

<%= link_to "投稿一覧に戻る", instagrams_path %>
    <%= render 'follow_form' %>
    <%= render 'stats' %>

app/views/users/show_follow.html.erb
<% @user.followings.each do |user| %>
    <table>
    <tr>
        <td>  <%= user.username %> </td>
        <td><%= link_to '詳細', user_path(user) %></td>
    </tr>
    <%= render 'follow_form' %>
    <%= render 'stats' %>
    </table>
    <% end %>

app/views/users/show_follower.html.erb
<% @user.followers.each do |user| %>
    <table>
    <tr>
        <td>  <%= user.username %> </td>
        <td><%= link_to '詳細', user_path(user) %></td>
    </tr>
    <%= render 'follow_form' %>
    <%= render 'stats' %>
    </table>
    <% end %>